"""
Normalize section names in mtsamples_staging.db chunks table.
Maps 1,581 noisy variants → ~60 canonical sections.

Run once before embedding:
    python normalize_sections.py
"""

import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "mtsamples_staging.db"

# Maps alias → canonical. All keys are uppercase, stripped.
SECTION_MAP = {
    # ── HISTORY OF PRESENT ILLNESS ──────────────────────────────────────
    "HPI": "HISTORY OF PRESENT ILLNESS",
    "HISTORY": "HISTORY OF PRESENT ILLNESS",
    "PRESENT ILLNESS": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF ILLNESS": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF PRESENT COMPLAINT": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF PRESENT PROBLEM": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF PRESENT INJURY": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF PRESENTING COMPLAINT": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF PRESENTING ILLNESS": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF PRESENTING PROBLEM": "HISTORY OF PRESENT ILLNESS",
    "HISTORY OF THE PRESENT ILLNESS": "HISTORY OF PRESENT ILLNESS",
    "BRIEF HISTORY OF PRESENT ILLNESS": "HISTORY OF PRESENT ILLNESS",
    "CURRENT HISTORY OF PRESENT ILLNESS": "HISTORY OF PRESENT ILLNESS",
    "CURRENT HISTORY": "HISTORY OF PRESENT ILLNESS",
    "INTERVAL HISTORY": "HISTORY OF PRESENT ILLNESS",
    "INTERIM HISTORY": "HISTORY OF PRESENT ILLNESS",
    "PRESENT COMPLAINTS": "HISTORY OF PRESENT ILLNESS",
    "PRESENT PROBLEMS": "HISTORY OF PRESENT ILLNESS",
    "PRESENTING PROBLEM": "HISTORY OF PRESENT ILLNESS",
    "PRESENTING PROBLEMS": "HISTORY OF PRESENT ILLNESS",
    "BRIEF HISTORY": "HISTORY OF PRESENT ILLNESS",
    "CLINICAL HISTORY": "HISTORY OF PRESENT ILLNESS",

    # ── PAST MEDICAL HISTORY ─────────────────────────────────────────────
    "PMH": "PAST MEDICAL HISTORY",
    "PAST MEDICAL HX": "PAST MEDICAL HISTORY",
    "PAST HISTORY": "PAST MEDICAL HISTORY",
    "PREVIOUS MEDICAL HISTORY": "PAST MEDICAL HISTORY",
    "PRIOR MEDICAL HISTORY": "PAST MEDICAL HISTORY",
    "PERTINENT MEDICAL HISTORY": "PAST MEDICAL HISTORY",
    "MEDICAL HISTORY": "PAST MEDICAL HISTORY",
    "ADULT MEDICAL PROBLEMS": "PAST MEDICAL HISTORY",
    "PAST MEDICAL CONDITIONS": "PAST MEDICAL HISTORY",
    "PRIMARY MEDICAL HISTORY": "PAST MEDICAL HISTORY",
    "PATIENT HISTORY": "PAST MEDICAL HISTORY",
    "PAST MEDICAL AND SURGICAL HISTORY": "PAST MEDICAL HISTORY",
    "PAST MEDICAL/SURGICAL HISTORY": "PAST MEDICAL HISTORY",
    "SIGNIFICANT PAST MEDICAL AND SURGICAL HISTORY": "PAST MEDICAL HISTORY",
    "OTHER SIGNIFICANT MEDICAL HISTORY/SURGERIES": "PAST MEDICAL HISTORY",
    "PAST MEDICAL HISTORY/SURGERIES/HOSPITALIZATIONS": "PAST MEDICAL HISTORY",
    "PAST MEDICAL HISTORY / SURGERY / HOSPITALIZATIONS": "PAST MEDICAL HISTORY",

    # ── PAST SURGICAL HISTORY ────────────────────────────────────────────
    "PSH": "PAST SURGICAL HISTORY",
    "PAST SURGICAL HX": "PAST SURGICAL HISTORY",
    "SURGICAL HISTORY": "PAST SURGICAL HISTORY",
    "PREVIOUS SURGICAL HISTORY": "PAST SURGICAL HISTORY",
    "PREVIOUS SURGERIES": "PAST SURGICAL HISTORY",
    "PRIOR SURGERIES": "PAST SURGICAL HISTORY",
    "PRIOR SURGERIES AND INTERVENTIONS": "PAST SURGICAL HISTORY",
    "PAST SURGERIES": "PAST SURGICAL HISTORY",
    "PREVIOUS OPERATIONS": "PAST SURGICAL HISTORY",

    # ── SOCIAL HISTORY ───────────────────────────────────────────────────
    "SHX": "SOCIAL HISTORY",
    "SOCIAL HX": "SOCIAL HISTORY",
    "SOCIAL": "SOCIAL HISTORY",
    "SOCH": "SOCIAL HISTORY",
    "SOCIAL HABITS": "SOCIAL HISTORY",
    "SOCIAL BACKGROUND": "SOCIAL HISTORY",
    "PERSONAL/SOCIAL HISTORY": "SOCIAL HISTORY",
    "PERSONAL AND SOCIAL HISTORY": "SOCIAL HISTORY",
    "PERSONAL HISTORY": "SOCIAL HISTORY",
    "SOCIOECONOMIC HISTORY": "SOCIAL HISTORY",
    "SOCIO-ECONOMIC HISTORY": "SOCIAL HISTORY",

    # ── FAMILY HISTORY ───────────────────────────────────────────────────
    "FHX": "FAMILY HISTORY",
    "FAMILY HX": "FAMILY HISTORY",
    "FAMILY MEDICAL HISTORY": "FAMILY HISTORY",
    "FAMILY BACKGROUND": "FAMILY HISTORY",
    "FAMILY PSYCHIATRIC HISTORY": "FAMILY HISTORY",

    # ── MEDICATIONS ──────────────────────────────────────────────────────
    "MEDS": "MEDICATIONS",
    "CURRENT MEDICATIONS": "MEDICATIONS",
    "CURRENT MEDS": "MEDICATIONS",
    "CURRENT MEDICATION": "MEDICATIONS",
    "CURRENT MEDICINES": "MEDICATIONS",
    "HOME MEDICATIONS": "MEDICATIONS",
    "MEDICATIONS AT HOME": "MEDICATIONS",
    "CURRENT HOME MEDICATIONS": "MEDICATIONS",
    "MEDICATION": "MEDICATIONS",
    "MEDICINES": "MEDICATIONS",
    "PRESENT MEDICATIONS": "MEDICATIONS",
    "OUTPATIENT MEDICATIONS": "MEDICATIONS",
    "INPATIENT MEDICATIONS": "MEDICATIONS",
    "MEDICATIONS OUTPATIENT": "MEDICATIONS",
    "MEDICATIONS INPATIENT": "MEDICATIONS",
    "MEDICATION HISTORY": "MEDICATIONS",
    "DRUG HISTORY": "MEDICATIONS",
    "OTHER MEDICATIONS": "MEDICATIONS",
    "NEW MEDICATIONS": "MEDICATIONS",
    "MEDS ON ADMISSION": "MEDICATIONS",
    "MEDICATIONS ON ADMISSION": "MEDICATIONS",
    "MEDICATIONS PRIOR TO ADMISSION": "MEDICATIONS",
    "CURRENT MEDS": "MEDICATIONS",

    # ── ALLERGIES ────────────────────────────────────────────────────────
    "DRUG ALLERGIES": "ALLERGIES",
    "MEDICATION ALLERGIES": "ALLERGIES",
    "ALLERGIES TO MEDICATIONS": "ALLERGIES",
    "ALLERGIC": "ALLERGIES",

    # ── PHYSICAL EXAMINATION ─────────────────────────────────────────────
    "PHYSICAL EXAM": "PHYSICAL EXAMINATION",
    "EXAM": "PHYSICAL EXAMINATION",
    "EXAMINATION": "PHYSICAL EXAMINATION",
    "PEX": "PHYSICAL EXAMINATION",
    "CLINICAL/PHYSICAL EXAMINATION": "PHYSICAL EXAMINATION",
    "ADMISSION PHYSICAL": "PHYSICAL EXAMINATION",
    "ADMIT EXAM": "PHYSICAL EXAMINATION",

    # ── VITAL SIGNS ──────────────────────────────────────────────────────
    "VITALS": "VITAL SIGNS",
    "VITAL SIGNS/GENERAL": "VITAL SIGNS",
    "CONSTITUTIONAL/VITAL SIGNS": "VITAL SIGNS",
    "BIOMETRIC DATA": "VITAL SIGNS",

    # ── REVIEW OF SYSTEMS ────────────────────────────────────────────────
    "ROS": "REVIEW OF SYSTEMS",
    "REVIEW OF SYSTEM": "REVIEW OF SYSTEMS",
    "REVIEW OF SYMPTOMS": "REVIEW OF SYSTEMS",
    "SYSTEMS REVIEW": "REVIEW OF SYSTEMS",
    "REVIEW OF BODY SYSTEMS": "REVIEW OF SYSTEMS",
    "SIGNIFICANT ILLNESS AND REVIEW OF SYSTEMS": "REVIEW OF SYSTEMS",

    # ── CHIEF COMPLAINT ──────────────────────────────────────────────────
    "CHIEF COMPLAINTS": "CHIEF COMPLAINT",
    "CHIEF COMPLIANT": "CHIEF COMPLAINT",
    "CHIEF COMPLAINT / REASON FOR THE VISIT": "CHIEF COMPLAINT",
    "CHIEF COMPLAINT - REASON FOR VISIT": "CHIEF COMPLAINT",
    "CHIEF COMPLAINT/HISTORY OF PRESENT ILLNESS": "CHIEF COMPLAINT",
    "CHIEF COMPLAINT AND IDENTIFICATION": "CHIEF COMPLAINT",
    "REASON FOR VISIT": "CHIEF COMPLAINT",
    "REASON FOR ADMISSION": "CHIEF COMPLAINT",
    "REASON FOR ADMISSION/CHIEF COMPLAINT": "CHIEF COMPLAINT",
    "REASON FOR HOSPITALIZATION": "CHIEF COMPLAINT",
    "REASON FOR CONSULT": "REASON FOR CONSULTATION",
    "REASON FOR REFERRAL": "REASON FOR CONSULTATION",
    "REASON FOR EVALUATION": "REASON FOR CONSULTATION",
    "CHIEF REASON FOR CONSULTATION": "REASON FOR CONSULTATION",
    "INDICATION FOR CONSULTATION": "REASON FOR CONSULTATION",

    # ── ASSESSMENT AND PLAN ──────────────────────────────────────────────
    "A/P": "ASSESSMENT AND PLAN",
    "ASSESSMENT & PLAN": "ASSESSMENT AND PLAN",
    "ASSESSMENT / PLAN": "ASSESSMENT AND PLAN",
    "ASSESSMENT/PLAN": "ASSESSMENT AND PLAN",
    "ASSESSMENT/PLAN/PROBLEMS": "ASSESSMENT AND PLAN",
    "IMPRESSION AND PLAN": "ASSESSMENT AND PLAN",
    "IMPRESSION/PLAN": "ASSESSMENT AND PLAN",
    "MPRESSION AND PLAN": "ASSESSMENT AND PLAN",
    "PLAN AND RECOMMENDATIONS": "ASSESSMENT AND PLAN",
    "PLAN/RECOMMENDATIONS": "ASSESSMENT AND PLAN",
    "PLAN / RECOMMENDATIONS": "ASSESSMENT AND PLAN",
    "DISCUSSION AND PLAN": "ASSESSMENT AND PLAN",
    "DISCUSSION/PLAN": "ASSESSMENT AND PLAN",
    "PLAN OF CARE": "ASSESSMENT AND PLAN",
    "PLAN/TREATMENT": "ASSESSMENT AND PLAN",
    "TREATMENT PLAN": "ASSESSMENT AND PLAN",
    "TREATMENT/PLAN": "ASSESSMENT AND PLAN",
    "EVALUATION/TREATMENT PLAN": "ASSESSMENT AND PLAN",
    "ASSESSMENT AND EVALUATION": "ASSESSMENT AND PLAN",
    "IMPRESSION DIAGNOSIS": "ASSESSMENT AND PLAN",
    "IMPRESSION / DIAGNOSIS": "ASSESSMENT AND PLAN",
    "FINAL IMPRESSION": "IMPRESSION",
    "OVERALL IMPRESSION": "IMPRESSION",
    "DIAGNOSTIC IMPRESSION": "IMPRESSION",
    "INITIAL IMPRESSION": "IMPRESSION",
    "CLINICAL IMPRESSION": "IMPRESSION",
    "IMPRESSIONS": "IMPRESSION",
    "IMPRESSION AT THIS TIME": "IMPRESSION",
    "IMPRESSION OF THE FINDINGS": "IMPRESSION",

    # ── ASSESSMENT ───────────────────────────────────────────────────────
    "ASSESSMENTS": "ASSESSMENT",
    "ASSESSMENT RESULTS": "ASSESSMENT",

    # ── DIAGNOSES ────────────────────────────────────────────────────────
    "DIAGNOSIS": "DIAGNOSES",
    "FINAL DIAGNOSIS": "DIAGNOSES",
    "FINAL DIAGNOSES": "DIAGNOSES",
    "CONCLUSIONS / FINAL DIAGNOSES": "DIAGNOSES",
    "PRIMARY DIAGNOSIS": "DIAGNOSES",
    "PRIMARY DIAGNOSES": "DIAGNOSES",
    "PRINCIPAL DIAGNOSIS": "DIAGNOSES",
    "PRINCIPAL DIAGNOSES": "DIAGNOSES",
    "CURRENT DIAGNOSES": "DIAGNOSES",
    "INITIAL DIAGNOSES": "DIAGNOSES",
    "PROBLEMS/DIAGNOSES": "DIAGNOSES",
    "PROBLEMS DIAGNOSES": "DIAGNOSES",
    "DIAGNOSES PROBLEMS": "DIAGNOSES",
    "DIFFERENTIAL DIAGNOSIS": "DIAGNOSES",
    "DIFFERENTIAL DIAGNOSES": "DIAGNOSES",

    # ── PREOPERATIVE DIAGNOSIS ───────────────────────────────────────────
    "PREOPERATIVE DIAGNOSES": "PREOPERATIVE DIAGNOSIS",
    "PREOP DIAGNOSIS": "PREOPERATIVE DIAGNOSIS",
    "PREOP DIAGNOSES": "PREOPERATIVE DIAGNOSIS",
    "PREOP DX": "PREOPERATIVE DIAGNOSIS",
    "PRE-OP DIAGNOSIS": "PREOPERATIVE DIAGNOSIS",
    "PRE-OP DIAGNOSES": "PREOPERATIVE DIAGNOSIS",
    "PRE-OPERATIVE DIAGNOSIS": "PREOPERATIVE DIAGNOSIS",
    "PRE-PROCEDURE DIAGNOSIS": "PREOPERATIVE DIAGNOSIS",
    "PREPROCEDURE DIAGNOSIS": "PREOPERATIVE DIAGNOSIS",
    "PREPROCEDURE DIAGNOSES": "PREOPERATIVE DIAGNOSIS",
    "PREOPERATIVE DX": "PREOPERATIVE DIAGNOSIS",
    "PREOPERATIVE DIAGNOSIS AND INDICATIONS": "PREOPERATIVE DIAGNOSIS",

    # ── POSTOPERATIVE DIAGNOSIS ──────────────────────────────────────────
    "POSTOPERATIVE DIAGNOSES": "POSTOPERATIVE DIAGNOSIS",
    "POSTOP DIAGNOSIS": "POSTOPERATIVE DIAGNOSIS",
    "POSTOP DIAGNOSES": "POSTOPERATIVE DIAGNOSIS",
    "POSTOP DX": "POSTOPERATIVE DIAGNOSIS",
    "POST-OP DIAGNOSIS": "POSTOPERATIVE DIAGNOSIS",
    "POST-OP DIAGNOSES": "POSTOPERATIVE DIAGNOSIS",
    "POST-OPERATIVE DIAGNOSIS": "POSTOPERATIVE DIAGNOSIS",
    "POST PROCEDURE DIAGNOSIS": "POSTOPERATIVE DIAGNOSIS",
    "POST-PROCEDURE DIAGNOSIS": "POSTOPERATIVE DIAGNOSIS",
    "POSTPROCEDURE DIAGNOSIS": "POSTOPERATIVE DIAGNOSIS",
    "POSTPROCEDURE DIAGNOSES": "POSTOPERATIVE DIAGNOSIS",
    "POSTOPERATIVE DX": "POSTOPERATIVE DIAGNOSIS",

    # ── PROCEDURE PERFORMED ──────────────────────────────────────────────
    "PROCEDURES PERFORMED": "PROCEDURE PERFORMED",
    "PROCEDURES  PERFORMED": "PROCEDURE PERFORMED",
    "PROCEDURE  PERFORMED": "PROCEDURE PERFORMED",
    "OPERATIVE PROCEDURE": "PROCEDURE PERFORMED",
    "OPERATIVE PROCEDURES": "PROCEDURE PERFORMED",
    "OPERATION PERFORMED": "PROCEDURE PERFORMED",
    "OPERATIONS PERFORMED": "PROCEDURE PERFORMED",
    "SURGICAL PROCEDURE": "PROCEDURE PERFORMED",
    "SURGICAL PROCEDURE PERFORMED": "PROCEDURE PERFORMED",
    "OPERATIVE PROCEDURE PERFORMED": "PROCEDURE PERFORMED",
    "PRIMARY OPERATIVE PROCEDURE": "PROCEDURE PERFORMED",
    "PRINCIPAL PROCEDURE": "PROCEDURE PERFORMED",
    "NAME OF OPERATION": "PROCEDURE PERFORMED",
    "NAME OF PROCEDURE": "PROCEDURE PERFORMED",
    "TITLE OF OPERATION": "PROCEDURE PERFORMED",
    "TITLE OF PROCEDURE": "PROCEDURE PERFORMED",
    "TITLE OF PROCEDURES": "PROCEDURE PERFORMED",
    "TITLE OF THE OPERATION": "PROCEDURE PERFORMED",
    "TITLE OF THE PROCEDURE": "PROCEDURE PERFORMED",
    "TYPE OF OPERATION": "PROCEDURE PERFORMED",
    "TYPE OF PROCEDURE": "PROCEDURE PERFORMED",
    "OPERATION AND PROCEDURE": "PROCEDURE PERFORMED",
    "OPERATION PROCEDURE": "PROCEDURE PERFORMED",
    "OPERATION/PROCEDURE": "PROCEDURE PERFORMED",
    "OPERATIONS": "PROCEDURE PERFORMED",
    "OPERATIONS AND PROCEDURES": "PROCEDURE PERFORMED",
    "OPERATION": "PROCEDURE PERFORMED",

    # ── PROCEDURE (body text) ────────────────────────────────────────────
    "PROCEDURES": "PROCEDURE",
    "PROCEDURES DONE": "PROCEDURE",
    "PROCEDURE DONE": "PROCEDURE",
    "PROCEDURE NOTE": "PROCEDURE",
    "PROCEDURE REPORT": "PROCEDURE",
    "PROCEDURE CODES": "PROCEDURE",
    "PROCEDURE AND FINDINGS": "PROCEDURE",
    "PROCEDURE AND TECHNIQUE": "PROCEDURE",

    # ── DESCRIPTION OF PROCEDURE ─────────────────────────────────────────
    "DESCRIPTION OF OPERATION": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF OPERATIONS": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF OPERATIVE PROCEDURE": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF SURGERY": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF TECHNIQUE": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF THE CASE": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF THE OPERATION": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF THE PROCEDURE": "DESCRIPTION OF PROCEDURE",
    "DESCRIPTION OF THE PROCEDURE IN DETAIL": "DESCRIPTION OF PROCEDURE",
    "PROCEDURE DETAIL": "DESCRIPTION OF PROCEDURE",
    "PROCEDURE DETAILS": "DESCRIPTION OF PROCEDURE",
    "PROCEDURE IN DETAIL": "DESCRIPTION OF PROCEDURE",
    "PROCEDURE PERFORMED IN DETAIL": "DESCRIPTION OF PROCEDURE",
    "DETAIL OF THE OPERATION": "DESCRIPTION OF PROCEDURE",
    "DETAILED OPERATIVE NOTE": "DESCRIPTION OF PROCEDURE",
    "DETAILS": "DESCRIPTION OF PROCEDURE",
    "DETAILS OF PROCEDURE": "DESCRIPTION OF PROCEDURE",
    "DETAILS OF THE OPERATION": "DESCRIPTION OF PROCEDURE",
    "DETAILS OF THE PROCEDURE": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE DETAILS": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE NARRATIVE": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE NOTE": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE NOTE IN DETAIL": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE REPORT": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE REPORT IN DETAIL": "DESCRIPTION OF PROCEDURE",
    "OPERATIVE TECHNIQUE": "DESCRIPTION OF PROCEDURE",
    "OPERATION IN DETAIL": "DESCRIPTION OF PROCEDURE",
    "NARRATIVE OF PROCEDURE": "DESCRIPTION OF PROCEDURE",
    "PROCEDURE AND INTERPRETATION": "DESCRIPTION OF PROCEDURE",
    "PROCEDURE DESCRIPTION": "DESCRIPTION OF PROCEDURE",
    "TECHNICAL PROCEDURE": "DESCRIPTION OF PROCEDURE",

    # ── NEUROLOGICAL ─────────────────────────────────────────────────────
    "NEUROLOGIC": "NEUROLOGICAL",
    "NEURO": "NEUROLOGICAL",
    "CNS": "NEUROLOGICAL",
    "CENTRAL NERVOUS SYSTEM": "NEUROLOGICAL",
    "NERVOUS SYSTEM": "NEUROLOGICAL",
    "GROSS NEUROLOGICAL EXAM": "NEUROLOGICAL",
    "OVERALL NEUROLOGICAL": "NEUROLOGICAL",
    "NEUROLOGIC EXAM": "NEUROLOGICAL",
    "NEUROLOGICAL EXAMINATION": "NEUROLOGICAL",

    # ── LABORATORY DATA ──────────────────────────────────────────────────
    "LAB": "LABORATORY DATA",
    "LABS": "LABORATORY DATA",
    "LAB DATA": "LABORATORY DATA",
    "LAB STUDIES": "LABORATORY DATA",
    "LAB TESTS": "LABORATORY DATA",
    "LABORATORY": "LABORATORY DATA",
    "LABORATORY RESULTS": "LABORATORY DATA",
    "LABORATORY STUDIES": "LABORATORY DATA",
    "LABORATORY TESTS": "LABORATORY DATA",
    "LABORATORY VALUES": "LABORATORY DATA",
    "LABORATORY FINDINGS": "LABORATORY DATA",
    "LABORATORY EXAMINATION": "LABORATORY DATA",
    "LABORATORY EXAM": "LABORATORY DATA",
    "LABORATORY AND DIAGNOSTIC DATA": "LABORATORY DATA",
    "LABORATORY AND X-RAY DATA": "LABORATORY DATA",
    "LABORATORY DATABASE": "LABORATORY DATA",
    "LABORATORY EVALUATION": "LABORATORY DATA",
    "PERTINENT LABORATORY DATA": "LABORATORY DATA",
    "PERTINENT LABORATORIES": "LABORATORY DATA",
    "LAB / TESTS": "LABORATORY DATA",
    "BLOOD STUDIES": "LABORATORY DATA",
    "DIAGNOSTIC DATA": "LABORATORY DATA",
    "DIAGNOSTIC STUDIES": "LABORATORY DATA",
    "DIAGNOSTIC AND LABORATORY DATA": "LABORATORY DATA",
    "DATA": "LABORATORY DATA",

    # ── HOSPITAL COURSE ──────────────────────────────────────────────────
    "COURSE": "HOSPITAL COURSE",
    "COURSE IN HOSPITAL": "HOSPITAL COURSE",
    "COURSE IN THE HOSPITAL": "HOSPITAL COURSE",
    "HOSPITAL COURSE AND TREATMENT": "HOSPITAL COURSE",
    "HOSPITAL COURSE PER PROBLEM LIST": "HOSPITAL COURSE",
    "HOSPITAL COURSE SUMMARY": "HOSPITAL COURSE",
    "HOSPITAL SUMMARY": "HOSPITAL COURSE",
    "BRIEF HOSPITAL COURSE": "HOSPITAL COURSE",
    "BRIEF HOSPITAL COURSE SUMMARY": "HOSPITAL COURSE",
    "BRIEF SUMMARY OF HOSPITAL COURSE": "HOSPITAL COURSE",

    # ── DISCHARGE DIAGNOSES ──────────────────────────────────────────────
    "DISCHARGE DIAGNOSIS": "DISCHARGE DIAGNOSES",
    "DIAGNOSES ON DISCHARGE": "DISCHARGE DIAGNOSES",
    "CONDITION AT DISCHARGE": "DISCHARGE DIAGNOSES",
    "ADDITIONAL DISCHARGE DIAGNOSES": "DISCHARGE DIAGNOSES",
    "PRIMARY DISCHARGE DIAGNOSES": "DISCHARGE DIAGNOSES",
    "SECONDARY DISCHARGE DIAGNOSES": "DISCHARGE DIAGNOSES",

    # ── INDICATIONS ──────────────────────────────────────────────────────
    "INDICATION": "INDICATIONS",
    "INDICATIONS FOR OPERATION": "INDICATIONS",
    "INDICATIONS FOR PROCEDURE": "INDICATIONS",
    "INDICATIONS FOR PROCEDURES": "INDICATIONS",
    "INDICATIONS FOR SURGERY": "INDICATIONS",
    "INDICATIONS FOR THE OPERATION": "INDICATIONS",
    "INDICATIONS FOR THE PROCEDURE": "INDICATIONS",
    "INDICATIONS FOR THE SURGERY": "INDICATIONS",
    "INDICATIONS FOR THIS PROCEDURE": "INDICATIONS",
    "INDICATIONS OF OPERATION": "INDICATIONS",
    "INDICATIONS OF PROCEDURE": "INDICATIONS",
    "INDICATIONS OF SURGERY": "INDICATIONS",
    "INDICATIONS OF THE PROCEDURE": "INDICATIONS",
    "INDICATIONS AND CONCERNS": "INDICATIONS",
    "INDICATION FOR OPERATION": "INDICATIONS",
    "INDICATION FOR PROCEDURE": "INDICATIONS",
    "INDICATION FOR STUDY": "INDICATIONS",
    "INDICATION FOR SURGERY": "INDICATIONS",
    "INDICATION FOR THE OPERATION": "INDICATIONS",
    "INDICATION FOR THE PROCEDURE": "INDICATIONS",
    "INDICATION FOR SURGERY": "INDICATIONS",
    "INDICATIONS FOR PROCEDURE": "INDICATIONS",
    "SURGICAL INDICATIONS": "INDICATIONS",
    "OPERATIVE INDICATIONS": "INDICATIONS",
    "PROCEDURE INDICATION": "INDICATIONS",
    "REASON FOR PROCEDURE": "INDICATIONS",
    "REASON FOR EXAM": "INDICATIONS",
    "REASON FOR EXAMINATION": "INDICATIONS",
    "REASON FOR CT SCAN": "INDICATIONS",
    "REASON FOR THE TEST": "INDICATIONS",
    "CLINICAL INDICATION": "INDICATIONS",
    "CLINICAL INDICATIONS": "INDICATIONS",
    "CLINICAL INFORMATION": "INDICATIONS",

    # ── GENERAL ──────────────────────────────────────────────────────────
    "GENERAL APPEARANCE": "GENERAL",
    "GEN": "GENERAL",
    "GEN EXAM": "GENERAL",
    "GENERAL OBSERVATIONS": "GENERAL",
    "GENERAL EVALUATION": "GENERAL",
    "GENERAL/CONSTITUTIONAL": "GENERAL",
    "CONSTITUTIONAL": "GENERAL",
    "CONSTITUTIONAL SYMPTOMS": "GENERAL",

    # ── FINDINGS ─────────────────────────────────────────────────────────
    "FINDING": "FINDINGS",
    "INTRAOPERATIVE FINDINGS": "FINDINGS",
    "INTRAOPERATIVE FINDING": "FINDINGS",
    "OPERATIVE FINDINGS": "FINDINGS",
    "GROSS FINDINGS": "FINDINGS",
    "DESCRIPTION OF FINDINGS": "FINDINGS",
    "FINDINGS AT OPERATION": "FINDINGS",
    "FINDINGS AT THE TIME OF SURGERY": "FINDINGS",
    "FINDINGS AT TIME OF SURGERY": "FINDINGS",
    "FINDINGS DURING THE PROCEDURE": "FINDINGS",
    "FINDINGS OF THE OPERATION": "FINDINGS",
    "ANGIOGRAPHIC FINDINGS": "FINDINGS",
    "ENDOSCOPIC FINDINGS": "FINDINGS",
    "GROSS INTRAOPERATIVE FINDINGS": "FINDINGS",
    "GROSS OPERATIVE FINDINGS": "FINDINGS",
    "POSTOPERATIVE FINDINGS": "FINDINGS",
    "PREOPERATIVE FINDINGS": "FINDINGS",
    "PATHOLOGICAL FINDINGS": "FINDINGS",
    "MAJOR FINDINGS": "FINDINGS",
    "PERTINENT FINDINGS": "FINDINGS",
    "SUMMARY OF FINDINGS": "FINDINGS",

    # ── HEENT ────────────────────────────────────────────────────────────
    "HEENT AND NECK": "HEENT",
    "HEENT/NECK": "HEENT",
    "ENMT": "HEENT",
    "ENT": "HEENT",
    "HEAD AND NECK": "HEENT",
    "HEAD AND NECK EXAMINATION": "HEENT",

    # ── CARDIOVASCULAR ───────────────────────────────────────────────────
    "CARDIOVASCULAR SYSTEM": "CARDIOVASCULAR",
    "CARDIOVASCULAR EXAM": "CARDIOVASCULAR",
    "CARDIAC": "CARDIOVASCULAR",
    "COR": "CARDIOVASCULAR",
    "CVS": "CARDIOVASCULAR",
    "CV - RESP": "CARDIOVASCULAR",
    "HEART": "CARDIOVASCULAR",

    # ── RESPIRATORY ──────────────────────────────────────────────────────
    "RESPIRATORY SYSTEM": "RESPIRATORY",
    "PULM": "RESPIRATORY",
    "PULMONARY": "RESPIRATORY",
    "LUNGS": "RESPIRATORY",
    "CHEST": "RESPIRATORY",

    # ── MUSCULOSKELETAL ──────────────────────────────────────────────────
    "MUSCULOSKELETAL SYSTEM": "MUSCULOSKELETAL",
    "MUSCULOSKELETAL/EXTREMITIES": "MUSCULOSKELETAL",
    "SKELETAL": "MUSCULOSKELETAL",
    "SKELETAL SYSTEM": "MUSCULOSKELETAL",
    "JOINTS": "MUSCULOSKELETAL",

    # ── GENITOURINARY ────────────────────────────────────────────────────
    "GENITOURINARY SYSTEM": "GENITOURINARY",
    "GU EXAM": "GENITOURINARY",
    "GU/RECTAL": "GENITOURINARY",
    "UROLOGIC": "GENITOURINARY",
    "UROLOGICAL": "GENITOURINARY",

    # ── GASTROINTESTINAL ─────────────────────────────────────────────────
    "GASTROINTESTINAL SYSTEM": "GASTROINTESTINAL",
    "ABDOMEN": "GASTROINTESTINAL",
    "ABD": "GASTROINTESTINAL",

    # ── PSYCHIATRIC ──────────────────────────────────────────────────────
    "PSYCHE": "PSYCHIATRIC",
    "PSYCH": "PSYCHIATRIC",
    "PSYCHOLOGICAL": "PSYCHIATRIC",
    "PSYCHOLOGIC": "PSYCHIATRIC",
    "MENTAL STATUS": "PSYCHIATRIC",
    "MENTAL STATUS EXAM": "PSYCHIATRIC",
    "MENTAL STATUS EXAMINATION": "PSYCHIATRIC",
    "MENTAL STATUS EVALUATION": "PSYCHIATRIC",
    "MSE": "PSYCHIATRIC",

    # ── SKIN ─────────────────────────────────────────────────────────────
    "DERMATOLOGIC": "SKIN",
    "DERM": "SKIN",
    "INTEGUMENTARY": "SKIN",

    # ── HEMATOLOGY ───────────────────────────────────────────────────────
    "HEMATOLOGIC": "HEMATOLOGY",
    "HEMATOLOGICAL": "HEMATOLOGY",
    "HEME/LYMPH": "HEMATOLOGY",
    "HEMATOPOIETIC": "HEMATOLOGY",
    "HEMATOLOGIC AND LYMPHATIC": "HEMATOLOGY",
    "HEMATOLOGIC/LYMPHATIC": "HEMATOLOGY",

    # ── RECOMMENDATIONS ──────────────────────────────────────────────────
    "RECOMMENDATION": "RECOMMENDATIONS",
    "PLAN AND SUGGESTION": "RECOMMENDATIONS",
    "PLANS/RECOMMENDATIONS": "RECOMMENDATIONS",
    "PLANS": "RECOMMENDATIONS",
    "ASSESSMENT AND RECOMMENDATIONS": "RECOMMENDATIONS",
    "EVALUATION/RECOMMENDATION": "RECOMMENDATIONS",

    # ── SUMMARY ──────────────────────────────────────────────────────────
    "SUMMARY AND CONCLUSIONS": "SUMMARY",
    "SUMMARY OF CLINICAL HISTORY": "SUMMARY",
    "CLINICAL SUMMARY": "SUMMARY",
    "CLINICAL RESUME": "SUMMARY",
    "IN SUMMARY": "SUMMARY",
    "ADMISSION SUMMARY": "SUMMARY",

    # ── ANESTHESIA ───────────────────────────────────────────────────────
    "ANESTHETIC": "ANESTHESIA",
    "ANESTHESIOLOGY": "ANESTHESIA",
    "ANESTHESIOLOGIST": "ANESTHESIA",
    "ANESTHESIA/SEDATION": "ANESTHESIA",
    "TYPE OF ANESTHESIA": "ANESTHESIA",
    "SECOND ANESTHESIA": "ANESTHESIA",
    "THIRD ANESTHESIA": "ANESTHESIA",
    "SEDATION": "ANESTHESIA",
    "LOCAL ANESTHETIC": "ANESTHESIA",
    "LOCAL": "ANESTHESIA",
    "IV SEDATION": "ANESTHESIA",

    # ── ESTIMATED BLOOD LOSS ─────────────────────────────────────────────
    "EBL": "ESTIMATED BLOOD LOSS",
    "BLOOD LOSS": "ESTIMATED BLOOD LOSS",

    # ── FLUIDS ───────────────────────────────────────────────────────────
    "FLUID": "FLUIDS",
    "IV FLUIDS": "FLUIDS",
    "INTRAVENOUS FLUIDS": "FLUIDS",
    "INTRAOPERATIVE FLUIDS": "FLUIDS",
    "FLUIDS GIVEN": "FLUIDS",
    "FLUIDS RECEIVED": "FLUIDS",
    "FLUID RECEIVED": "FLUIDS",
    "FLUID REPLACEMENT": "FLUIDS",
    "CRYSTALLOIDS": "FLUIDS",

    # ── COMPLICATIONS ────────────────────────────────────────────────────
    # keep as-is

    # ── DISPOSITION ──────────────────────────────────────────────────────
    "DISCHARGE DISPOSITION": "DISPOSITION",
    "CONDITION ON DISPOSITION": "DISPOSITION",
    "CONDITION UPON DISPOSITION": "DISPOSITION",
    "AFTERCARE AND DISPOSITION": "DISPOSITION",
    "POST-PROCEDURE COURSE AND DISPOSITION": "DISPOSITION",

    # ── RADIOLOGY ────────────────────────────────────────────────────────
    "RADIOLOGIC DATA": "RADIOLOGY",
    "RADIOLOGICAL DATA": "RADIOLOGY",
    "RADIOGRAPHIC DATA": "RADIOLOGY",
    "RADIOGRAPHIC STUDIES": "RADIOLOGY",
    "RADIOGRAPHS": "RADIOLOGY",
    "IMAGING": "RADIOLOGY",
    "IMAGING STUDIES": "RADIOLOGY",
    "IMAGING DATA": "RADIOLOGY",
    "DIAGNOSTIC IMAGING": "RADIOLOGY",
    "MEDICAL IMAGING": "RADIOLOGY",
    "X-RAYS": "RADIOLOGY",
    "X-RAY AND LABORATORY DATA": "RADIOLOGY",
    "X-RAY INTERPRETATION": "RADIOLOGY",

    # ── TECHNIQUE ────────────────────────────────────────────────────────
    "IMAGE TECHNIQUE": "TECHNIQUE",
    "PROCEDURE TECHNIQUE": "TECHNIQUE",
    "STUDY PROTOCOL": "TECHNIQUE",
    "NUCLEAR PROTOCOL": "TECHNIQUE",
    "STRESS TECHNIQUE": "TECHNIQUE",

    # ── SUBJECTIVE / OBJECTIVE (SOAP) ────────────────────────────────────
    "SUBJECTIVE COMPLAINTS": "SUBJECTIVE",

    # ── FOLLOW-UP ────────────────────────────────────────────────────────
    "FOLLOW UP": "FOLLOW-UP",
    "FOLLOWUP": "FOLLOW-UP",
    "FOLLOW-UP APPOINTMENT": "FOLLOW-UP",
    "FOLLOWUP APPOINTMENTS": "FOLLOW-UP",
    "FOLLOWUP CARE": "FOLLOW-UP",
    "DISCHARGE FOLLOWUP": "FOLLOW-UP",
    "DISCHARGE FOLLOWUP PLANNING": "FOLLOW-UP",
    "OUTPATIENT CARE": "FOLLOW-UP",

    # ── SPECIMENS ────────────────────────────────────────────────────────
    "SPECIMEN": "SPECIMENS",
    "PATHOLOGY": "SPECIMENS",
    "PATHOLOGY SPECIMEN": "SPECIMENS",
    "GROSS DESCRIPTION": "SPECIMENS",
    "MICROSCOPIC DESCRIPTION": "SPECIMENS",
    "MICROSCOPIC EXAMINATION": "SPECIMENS",
}


def normalize_section(section: str) -> str:
    """Normalize a section name to canonical form."""
    if not section:
        return section
    key = section.strip().upper()
    return SECTION_MAP.get(key, key)


def run():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cur.execute("SELECT COUNT(DISTINCT section) FROM chunks")
    before = cur.fetchone()[0]
    print(f"Distinct sections before: {before}")

    # fetch all unique sections that have a mapping
    cur.execute("SELECT DISTINCT section FROM chunks")
    all_sections = [r[0] for r in cur.fetchall()]

    updated_total = 0
    for section in all_sections:
        canonical = normalize_section(section)
        if canonical != section:
            cur.execute(
                "UPDATE chunks SET section = ? WHERE section = ?",
                (canonical, section),
            )
            updated_total += cur.rowcount

    conn.commit()

    cur.execute("SELECT COUNT(DISTINCT section) FROM chunks")
    after = cur.fetchone()[0]
    print(f"Distinct sections after:  {after}")
    print(f"Rows updated: {updated_total:,}")
    print(f"Sections collapsed: {before - after}")

    # show top 30 canonical sections
    cur.execute(
        "SELECT section, COUNT(*) as cnt FROM chunks GROUP BY section ORDER BY cnt DESC LIMIT 30"
    )
    print("\nTop 30 canonical sections:")
    for row in cur.fetchall():
        print(f"  {row[1]:5d}  {row[0]}")

    conn.close()


if __name__ == "__main__":
    run()
